Repository MilindGupta-Creator/Competitive-Coding-Section, pull requests merged in 2022-10, with the labels that each got.

#67 Add the problem solution of Making a Meal .cpp
  Codechef Beginner/Making a Meal.cpp
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#72 Created a separate folder for Binary Search and added the read.me as well
  Binary Search/Binary_Search.cpp
  Binary Search/read.md
  Dynamic Programming/0_1_Knapsack.cpp
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#91 dp problems
  Dynamic Programming/distinct_subsequences.cpp
  Dynamic Programming/dungeon_game.cpp
  Dynamic Programming/edit_distance.cpp
  Dynamic Programming/maximum_product_subarray.cpp
  Dynamic Programming/wildcard_matching.cpp
Labels: documentation, algorithm, hacktoberfest-accepted

#92 add java folder
  JavaSolution/bookAllocation.java
Labels: hacktoberfest, algorithm, DataStructure, hacktoberfest-accepted

#88 [Hacktoberfest] Added aggressive_cows solution approach
  Binary Search/AggresiveCows.cpp
  binary-search-approaches
Labels: good first issue, hacktoberfest, algorithm, DataStructure, hacktoberfest-accepted

#96 Added binary search problem
  Binary Search/First_And_Last_Occurence_of_Element.cpp
Labels: documentation, good first issue, hacktoberfest, DataStructure, hacktoberfest-accepted

#95 HACKTOBERFEST-2022
  GFG Solutions/C++/ReverseLLinkthorder.cpp
  GFG Solutions/sieveoferoth.cpp
Labels: good first issue, hacktoberfest, algorithm, hacktoberfest-accepted

#83 Create Median-of-2-sorted-arrays.cpp
  Algorithm/Median-of-2-sorted-arrays.cpp
Labels: good first issue, hacktoberfest, algorithm, hacktoberfest-accepted

#112 added dutch national flag algorithm in cpp
  Algorithm/dutch_national_flag.cpp
  Binary Search/median_of_two_sorted_arrays.cpp
  GFG Solutions/count_all_possible_paths_from_top_left_to_bottom_right.cpp
Labels: documentation, good first issue, hacktoberfest, algorithm, DataStructure, hacktoberfest-accepted

#110 O(log(N))
  Binary Search/Count_of_an_Element_SortedArray.cpp
Labels: documentation, good first issue, hacktoberfest, algorithm, hacktoberfest-accepted

#93 leetcode easy problems added
  leetcode problems/build_array_from_permutation.cpp
  leetcode problems/check_distances_btw_same_letters.cpp
  leetcode problems/divide_string_into_k_groups.cpp
  leetcode problems/find_target_indices_after_sorting_array.cpp
  leetcode problems/first_pallidrome.cpp
  leetcode problems/gcd.cpp
  leetcode problems/maximum_population_year.cpp
  leetcode problems/rings_and_rods.cpp
  leetcode problems/sort_odd_even_indices.cpp
  leetcode problems/two_furthest_house_same_color.cpp
Labels: documentation, good first issue, hacktoberfest, algorithm, DataStructure, hacktoberfest-accepted

#143 roatate_array.cpp
  leetcode problems/roatate_array.cpp
Labels: good first issue, hacktoberfest, algorithm, DataStructure, hacktoberfest-accepted

#142 house_robber.cpp
  house_robber.cpp
Labels: good first issue, hacktoberfest, algorithm, DataStructure, hacktoberfest-accepted
